# Generated by Django 4.2.20 on 2025-03-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdiscussion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectdiscussion',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='projectdiscussion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectdiscussionmessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectdiscussionmessage',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='projectdiscussionmessage',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='projectdiscussionmessage',
            name='reply_of',
        ),
        migrations.DeleteModel(
            name='ProjectComment',
        ),
        migrations.DeleteModel(
            name='ProjectDiscussion',
        ),
        migrations.DeleteModel(
            name='ProjectDiscussionMessage',
        ),
    ]
