# Generated by Django 4.2.20 on 2025-03-23 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('task_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='tasks.taskcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('task_comment', 'user')},
            },
        ),
    ]
