# Generated by Django 4.2.20 on 2025-03-22 18:44

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.conf import settings

from accounts.permissions import group_permission_mapping


def create_groups_and_permissions(apps, schema_editor):
    for group_name in settings.ALLOWED_USER_GROUPS:
        group, _ = Group.objects.get_or_create(name=group_name)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
    ]
